//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public string project_id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> start { get; set; }
        public Nullable<System.DateTime> end { get; set; }
        public string teacher_id { get; set; }
        public string student_id { get; set; }
        public int ID { get; set; }
    
        public virtual studen studen { get; set; }
        public virtual teacher teacher { get; set; }
    }
}
